CREATE TABLE trains (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY    
);

CREATE TABLE platforms (
    name VARCHAR(256) NOT NULL PRIMARY KEY  
);

CREATE TABLE carriages (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    train_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (train_id) REFERENCES trains(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE platform_sensors (
    address VARCHAR(17) NOT NULL PRIMARY KEY,
    platform_name VARCHAR(256) NOT NULL,
    position INT UNSIGNED NOT NULL,
    FOREIGN KEY (platform_name) REFERENCES platforms(name) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE carriage_sensors (
    address VARCHAR(17) NOT NULL PRIMARY KEY,
    carriage_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (carriage_id) REFERENCES carriages(id) ON DELETE RESTRICT ON UPDATE CASCADE
);