CREATE TABLE trains (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE platforms (
    name VARCHAR(256) NOT NULL PRIMARY KEY
);

CREATE TABLE carriages (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    position INT UNSIGNED NOT NULL,
    train_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (train_id) REFERENCES trains(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE platform_sensors (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    platform_name VARCHAR(256) NOT NULL,
    relative_position DOUBLE NOT NULL,
    FOREIGN KEY (platform_name) REFERENCES platforms(name) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE carriage_sensors (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    carriage_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (carriage_id) REFERENCES carriages(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO trains () VALUES (), (), ();

INSERT INTO carriages (train_id, position) VALUES (1, 1), (1, 2), (2, 1), (2, 2), (3, 1), (3, 2);

INSERT INTO platforms (name) VALUES ('Kista'), ('T-Central');

INSERT INTO platform_sensors (uuid, platform_name, relative_position) VALUES ('AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA', 'Kista', 0.33), ('BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB', 'Kista', 0.67), ('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC', 'T-Central', 0.33), ('DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD', 'T-Central', 0.67);

INSERT INTO carriage_sensors (uuid, carriage_id) VALUES ('EEEEEEEE-EEEE-EEEE-EEEE-EEEEEEEEEEEE', 1), ('FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF', 2), ('GGGGGGGG-GGGG-GGGG-GGGG-GGGGGGGGGGGG', 3), ('HHHHHHHH-HHHH-HHHH-HHHH-HHHHHHHHHHHH', 4), ('IIIIIIII-IIII-IIII-IIII-IIIIIIIIIIII', 5), ('JJJJJJJJ-JJJJ-JJJJ-JJJJ-JJJJJJJJJJJJ', 6);